openapi: 3.0.1
info:
  title: testDRGApi
  description: API Definition of testDRGApi
  version: 1.0.0
servers:
- url: http://localhost:8290/testdrgapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
